"use client";

import React, { useState } from "react";
import { Play, Shuffle, Clock, ListPlus, Send, BrainCircuit } from "lucide-react";
import { usePlayerStore } from "../../store/usePlayerStore";
import { useAIStore } from "../../store/useAIStore";

export function AIPlaylistView({ playlist }) {
  const { playTrack } = usePlayerStore();
  const { modifyActivePlaylist, loading } = useAIStore();
  const [modifyInput, setModifyInput] = useState("");

  if (!playlist) return null;

  const tracks = playlist.tracks || [];

  const handlePlayAll = () => {
    if (tracks.length > 0) {
      playTrack(tracks[0], tracks);
    }
  };

  const handleShuffle = () => {
    if (tracks.length > 0) {
      const shuffled = [...tracks].sort(() => Math.random() - 0.5);
      playTrack(shuffled[0], shuffled);
    }
  };

  const handleAddToQueue = () => {
    if (tracks.length > 0) {
      const currentQueue = usePlayerStore.getState().queue;
      usePlayerStore.setState({ queue: [...currentQueue, ...tracks] });
    }
  };

  const handleModifySubmit = (e) => {
    e.preventDefault();
    if (!modifyInput.trim()) return;
    modifyActivePlaylist(modifyInput.trim());
    setModifyInput("");
  };

  const formatDuration = (seconds) => {
    if (!seconds) return "3:00";
    const mins = Math.floor(seconds / 60);
    const secs = Math.floor(seconds % 60);
    return `${mins}:${secs < 10 ? "0" : ""}${secs}`;
  };

  const totalMins = Math.round(
    tracks.reduce((acc, t) => acc + (t.duration || 180), 0) / 60
  );

  return (
    <div className="w-full bg-zinc-900/90 border border-white/10 rounded-xl p-3 shadow-xl text-white space-y-3">
      {/* Header Info */}
      <div className="flex items-start gap-2.5 border-b border-white/10 pb-2.5">
        <div className="w-9 h-9 rounded-lg bg-gradient-to-br from-indigo-600 via-purple-600 to-pink-500 flex items-center justify-center text-white shadow-md shrink-0">
          <BrainCircuit className="w-5 h-5 animate-pulse" />
        </div>
        <div className="min-w-0 flex-1">
          <div className="flex items-center gap-1.5 flex-wrap">
            <span className="text-[9px] font-semibold px-1.5 py-0.5 rounded bg-indigo-500/20 text-indigo-300 border border-indigo-500/30 uppercase tracking-wider">
              AI Playlist
            </span>
            {playlist.mood && (
              <span className="text-[9px] px-1.5 py-0.5 rounded bg-zinc-800 text-zinc-300 capitalize">
                {playlist.mood}
              </span>
            )}
          </div>
          <h4 className="text-xs font-bold mt-1 text-white truncate">
            {playlist.title || "Custom AI Playlist"}
          </h4>
          <p className="text-[10px] text-zinc-400 line-clamp-1 mt-0.5">
            {playlist.description || "Generated by Ask Sonique AI"}
          </p>
          <div className="flex items-center gap-2 text-[10px] text-zinc-400 mt-1">
            <span>{tracks.length} songs</span>
            <span>•</span>
            <span className="flex items-center gap-1">
              <Clock className="w-3 h-3 text-zinc-400" /> ~{totalMins} mins
            </span>
          </div>
        </div>
      </div>

      {/* Action Controls */}
      <div className="flex items-center gap-1.5 flex-wrap">
        <button
          onClick={handlePlayAll}
          className="flex-1 min-w-[70px] flex items-center justify-center gap-1 px-2.5 py-1.5 bg-indigo-600 hover:bg-indigo-500 text-white font-medium rounded-lg transition text-xs shadow-md shadow-indigo-600/30"
        >
          <Play className="w-3 h-3 fill-white" /> Play All
        </button>
        <button
          onClick={handleShuffle}
          className="flex items-center justify-center gap-1 px-2 py-1.5 bg-zinc-800 hover:bg-zinc-700 text-zinc-200 font-medium rounded-lg transition text-xs"
        >
          <Shuffle className="w-3 h-3" /> Shuffle
        </button>
        <button
          onClick={handleAddToQueue}
          className="flex items-center justify-center gap-1 px-2 py-1.5 bg-zinc-800 hover:bg-zinc-700 text-zinc-200 font-medium rounded-lg transition text-xs"
          title="Add to queue"
        >
          <ListPlus className="w-3 h-3" /> Queue
        </button>
      </div>

      {/* Modify Playlist Form */}
      <form onSubmit={handleModifySubmit} className="flex gap-1.5">
        <input
          type="text"
          value={modifyInput}
          onChange={(e) => setModifyInput(e.target.value)}
          placeholder="Modify (e.g. 'Remove sad songs')..."
          className="flex-1 bg-zinc-950/70 border border-white/10 rounded-lg px-2.5 py-1 text-[11px] text-white placeholder-zinc-500 focus:outline-none focus:border-indigo-500 transition min-w-0"
          disabled={loading}
        />
        <button
          type="submit"
          disabled={loading || !modifyInput.trim()}
          className="px-2.5 py-1 bg-indigo-600/80 hover:bg-indigo-500 disabled:opacity-50 text-white font-medium rounded-lg text-xs flex items-center gap-1 transition shrink-0"
        >
          <Send className="w-3 h-3" /> Modify
        </button>
      </form>

      {/* Responsive Scrollable Track List */}
      <div className="space-y-1 max-h-48 overflow-y-auto pr-1 scrollbar-thin scrollbar-thumb-zinc-800">
        {tracks.map((track, idx) => (
          <div
            key={track.videoId || track.id || idx}
            onClick={() => playTrack(track, tracks)}
            className="flex items-center justify-between p-1.5 rounded-lg hover:bg-white/5 transition cursor-pointer group gap-2"
          >
            <div className="flex items-center gap-2 min-w-0 flex-1">
              <span className="w-4 text-center text-[10px] text-zinc-500 font-medium group-hover:text-indigo-400 shrink-0">
                {idx + 1}
              </span>
              <img
                src={track.coverUrl || track.thumbnail || "/default-cover.jpg"}
                alt={track.title}
                className="w-7 h-7 rounded object-cover bg-zinc-800 shrink-0"
              />
              <div className="min-w-0 flex-1">
                <p className="text-xs font-medium text-white truncate group-hover:text-indigo-300">
                  {track.title}
                </p>
                <p className="text-[10px] text-zinc-400 truncate">{track.artist}</p>
              </div>
            </div>
            <span className="text-[10px] text-zinc-500 shrink-0">
              {formatDuration(track.duration)}
            </span>
          </div>
        ))}
      </div>
    </div>
  );
}
